exp_name: 

sigma_begin: 1
sigma_end: 0.01
num_t_steps: 10

model:
  type: 'NoiseConditionedScoreNet'
  t_steps: 10

optimizer:
  type: 'Adam'
  args:
    lr: 1e-3

trainer:
  type: 'NCSNTrainer'

data:
  type: 'swiss'
  size: 10000
  path: 'swiss.pickle'

sampler:
  type: 'AnnealedLangevinSampler'
  run:
    n_steps: 100

steps: 60_000
log_freq: 6_000
save_freq: 6_000