exp_name: 

sigma_begin: 20
sigma_end: 1
num_t_steps: 10

model:
  type: 'NoiseConditionedScoreNet'
  t_steps: 10

optimizer:
  type: 'AdamW'
  args:
    lr: 0.001
    weight_decay: 0.0001

trainer:
  type: 'NCSNTrainer'

data:
  type: 'gauss'
  size: 1280
  path: 'gauss.pickle'

sampler:
  type: 'AnnealedLangevinSampler'
  run:
    n_steps: 100
    eps: 0.1

steps: 60_000
log_freq: 10_000
save_freq: 10_000