exp_name: 

sigma: 0.1

model:
  type: 'ScoreNet'

optimizer:
  type: 'SGD'
  args:
    lr: 1e-3

trainer:
  type: 'SimpleTrainer'

data:
  type: 'circle'
  size: 1280
  path: 'circle.pickle'

sampler:
  type: 'LangevinSampler'
  run:
    n_steps: 100
    eps: 0.001

steps: 60_000
log_freq: 6_000
save_freq: 6_000