exp_name: 

sigma: 0.01

model:
  type: 'ScoreNet'

optimizer:
  type: 'SGD'
  args:
    lr: 1e-3

trainer:
  type: 'SimpleTrainer'

data:
  type: 'swiss'
  size: 10000
  path: 'swiss.pickle'

sampler:
  type: 'SimpleSampler'
  run:
    n_steps: 100

steps: 60_000
log_freq: 6_000
save_freq: 6_000